// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
export { InParentNamespace, InParentNamespaceT } from './my-game/in-parent-namespace.d.ts';
export * as Example from './my-game/example.d.ts';
export * as Example2 from './my-game/example2.d.ts';
export * as OtherNameSpace from './my-game/other-name-space.d.ts';
