// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
export { Ability, AbilityT } from './example/ability.d.ts';
export { Any } from './example/any.d.ts';
export { AnyAmbiguousAliases } from './example/any-ambiguous-aliases.d.ts';
export { AnyUniqueAliases } from './example/any-unique-aliases.d.ts';
export { Color } from './example/color.d.ts';
export { LongEnum } from './example/long-enum.d.ts';
export { Monster, MonsterT } from './example/monster.d.ts';
export { Race } from './example/race.d.ts';
export { Referrable, ReferrableT } from './example/referrable.d.ts';
export { Stat, StatT } from './example/stat.d.ts';
export { StructOfStructs, StructOfStructsT } from './example/struct-of-structs.d.ts';
export { StructOfStructsOfStructs, StructOfStructsOfStructsT } from './example/struct-of-structs-of-structs.d.ts';
export { Test, TestT } from './example/test.d.ts';
export { TestSimpleTableWithEnum, TestSimpleTableWithEnumT } from './example/test-simple-table-with-enum.d.ts';
export { TypeAliases, TypeAliasesT } from './example/type-aliases.d.ts';
export { Vec3, Vec3T } from './example/vec3.d.ts';
