// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
export { ArrayStruct, ArrayStructT } from './example/array-struct.d.ts';
export { ArrayTable, ArrayTableT } from './example/array-table.d.ts';
export { InnerStruct, InnerStructT } from './example/inner-struct.d.ts';
export { NestedStruct, NestedStructT } from './example/nested-struct.d.ts';
export { OuterStruct, OuterStructT } from './example/outer-struct.d.ts';
export { TestEnum } from './example/test-enum.d.ts';
